from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)


def create_pdf(
    filename,
    score,
    skills,
    missing_skills,
    suggestions
):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    # ==========================
    # Title
    # ==========================

    story.append(
        Paragraph(
            "<b>Smart Resume Analyzer Report</b>",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 20))

    # ==========================
    # Resume Score
    # ==========================

    story.append(
        Paragraph(
            f"<b>Resume Score :</b> {score}/100",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 15))

    # ==========================
    # Skills
    # ==========================

    story.append(
        Paragraph(
            "<b>Detected Skills</b>",
            styles["Heading2"]
        )
    )

    if skills:

        for skill in skills:

            story.append(
                Paragraph(
                    "• " + skill,
                    styles["BodyText"]
                )
            )

    else:

        story.append(
            Paragraph(
                "No skills detected.",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1, 15))

    # ==========================
    # Missing Skills
    # ==========================

    story.append(
        Paragraph(
            "<b>Missing Skills</b>",
            styles["Heading2"]
        )
    )

    if missing_skills:

        for skill in missing_skills:

            story.append(
                Paragraph(
                    "• " + skill,
                    styles["BodyText"]
                )
            )

    else:

        story.append(
            Paragraph(
                "No missing skills.",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1, 15))

    # ==========================
    # Suggestions
    # ==========================

    story.append(
        Paragraph(
            "<b>Resume Suggestions</b>",
            styles["Heading2"]
        )
    )

    if suggestions:

        for item in suggestions:

            story.append(
                Paragraph(
                    "• " + item,
                    styles["BodyText"]
                )
            )

    else:

        story.append(
            Paragraph(
                "No suggestions.",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1, 20))

    # ==========================
    # Footer
    # ==========================

    story.append(
        Paragraph(
            "<b>Generated by Smart Resume Analyzer</b>",
            styles["Italic"]
        )
    )

    doc.build(story)